version: 0.2

phases:
  install:
    -runtime-version:
      nodejs: 20.x
  build:
    commands:
      - echo Test started on `date`
      - npn run test
artifacts:
  files:
    - '**/*'
  discard-paths: no
  